// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "2c0901e5-a7ed-42c6-b385-a0f82b5d6f99";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onManualBuzzerChange();
void onManualGreenChange();
void onManualRedChange();

String last_test_time;
String status;
float bac_percent;
int bac_raw;
int heart_rate;
int spo2;
bool manual_buzzer;
bool manual_green;
bool manual_red;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(last_test_time, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(status, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(bac_percent, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(bac_raw, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(heart_rate, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(spo2, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(manual_buzzer, READWRITE, ON_CHANGE, onManualBuzzerChange);
  ArduinoCloud.addProperty(manual_green, READWRITE, ON_CHANGE, onManualGreenChange);
  ArduinoCloud.addProperty(manual_red, READWRITE, ON_CHANGE, onManualRedChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
